name: GE

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
#  - python=3.7.9
  - pip
  - pytorch
  - torchvision
#  - torchaudio
  - matplotlib
  - numpy
  - pandas
#  - scipy
#  - pyyaml
#  - tqdm
#  - git
#  - pip:
#      - git+https://github.com/hassony2/chumpy.git
#      - trimesh
#      - pyrender
#      - open3d
#      - opencv-python==4.3.0.36
#      - opencv-contrib-python~=4.3.0.36
